# Generated by Django 5.2 on 2025-04-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr', models.IntegerField(default=0)),
                ('date', models.DateField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('t_id', models.IntegerField(default=0)),
                ('sender', models.CharField(default=0, max_length=100)),
                ('receiver', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
