# Generated by Django 5.2 on 2025-04-23 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qist',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
